#
###################################
# Site wide configuration
####################################
#
title: Anand
email: anandhjoshi@outlook.com
description: My diary
url: # the base hostname & protocol for your site

#
###################################
# Pagination
###################################
gems: [jekyll-paginate]
paginate: 5

#
###################################
# Jekyll configuration
####################################
#
timezone:          India/Mumbai
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Anand Joshi
  avatar: anand.png
  job: "I am crazy and I know it !"
  bio: "Developer|Blogger|Musician|Traveller"
  email: anandhjoshi@outlook.com
  disqus-shortname: disqus-xhnqvb9w3g
  twitter: #username
  facebook: anand.joshi.790
  google:
    plus: 
    analytics: UA-85824802-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: anandjoshi91
  gitlab: #username
  stackoverflow: 6143348/anand-joshi
  linkedin: #username
  skype: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
