#
###################################
# Site wide configuration
####################################
#
title: Anand
email: anandhjoshi@outlook.com
description: "Random articles on topics from programming to pink-floyd"
url: https://anandjoshi.me

#
###################################
# Plugins
###################################
plugins: [jekyll-paginate]
paginate: 5


#
###################################
# Jekyll configuration
####################################
#
timezone:          Asia/Calcutta
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title
exclude: ['README.md','LICENSE.txt','CNAME']
include: ['.htaccess']

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Anand Joshi
  avatar: anand.jpg
  job: "Random thoughts & Stories"
  bio: "Developer|Blogger|Musician|Traveller"
  email: admin@anandjoshi.me
  disqus-shortname: disqus-xhnqvb9w3g
  twitter: Anand_Jos
  facebook: anand.joshi.790
  google:
    plus: 
    analytics: UA-85824802-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: anandjoshi91
  gitlab: #username
  stackoverflow: 6143348/anand-joshi
  linkedin: anandhjoshi
  skype: #username
  xing: #username
  instagram: anand.joshi.790
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: anand-joshi-5
  weibo: #username
  flickr: #username
  500px: anandjoshi5
  codepen: #username
